security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        users_doctrine:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: users_doctrine
            guard:
                authenticator:
                    - App\Security\Guard\WebAuthenticator
            logout:
                path: security_logout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_UTILISATEUR: [ROLE_USER]
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
